## DaylightSavingTime.R or equivalent should be sourced before calling these functions

## create rulesFinCenter() here to shadow the one in timeDate
rulesFinCenter <-
function (FinCenter) { ## without default here, on purpose
    if (any(FinCenter %in% c("GMT", "UTC", " "))) 
        stop("There are no DST rules for GMT FinCenter!")
    fccity <- strsplit(FinCenter, "/")[[1]]
    City <- fccity[length(fccity)]
    fun <- get(City, mode = "function")
    fun()
}


udf_sort <- function(fc_list = listFinCenter()) {
    fc <- fc_list[1]
    if(fc == "Easter")
        fc <- "Easter_Island"
    wrk <- rulesFinCenter(fc)
    colnames(wrk)[1] <- "LocalTime"
    df <- wrk

    for(fc in fc_list[-1]){
        if(fc == "Easter")
            fc <- "Easter_Island"
        wrk <- rulesFinCenter(fc)
        colnames(wrk)[1] <- "LocalTime"
        df <- rbind(df, wrk)
    }

    udf <- unique(df)
    tmp_ind <- order(udf[ , "LocalTime"])
    udf_sorted <- udf[tmp_ind, ]

    udf_sorted
}


get_fc_index <- function(fc, df_all){
    if(fc == "Easter")
        fc <- "Easter_Island"

    wrk <- rulesFinCenter(fc)
    colnames(wrk)[1] <- "LocalTime"
    tmpdf <- rbind(df_all, wrk)
    indx <- which(duplicated(tmpdf, fromLast = TRUE))

    df <- tmpdf[indx, , drop = FALSE]
    rownames(df) <- NULL
    colnames(df)[1] <- fc

    if(!identical(rulesFinCenter(fc), df)){
        print(paste0("get_fc_index: the created df for ", fc,
                     " is not identical to the original\n"))
        browser()
    }
     indx
}

fc_index_to_df <- function(indx, df_all, fc){
    df <- df_all[indx, , drop = FALSE]
    rownames(df) <- NULL
    colnames(df)[1] <- fc

    if(!identical(rulesFinCenter(fc), df))
        print(paste0("fc_index_to_df: the created df for ", fc,
                     "is not identical to the original\n"))
    df
}


dput_fc <- function(fc, df_all, name_df_all = "all_tz_rows", cache = "tzdb_cache",
                    file = "", append = TRUE){
    if(fc == "Easter")
        fc <- "Easter_Island"

    indx <- get_fc_index(fc, df_all)
    indx_dput <- capture.output(dput(indx))
    indx_dput <- paste(indx_dput, collapse = "\n             ")
    cat("\n\n",
        '"', fc, '"', " <- ", "function() {\n",
        "    if(!is.null(", cache, '[["', fc, '"]]', "))\n",
        "        return(", cache, '[["', fc, '"]]', ")\n",
        "    ind <- ", indx_dput, "\n",
        "    ", "res <- ", name_df_all, "[", "ind, ", "]\n",
        "    ", 'colnames(res)[1] <- "', fc, '"\n',
        "    ", "rownames(res) <- NULL\n",
        "    ", cache, '[["', fc, '"]] <- res\n',
        "    ", "res\n",
        "}\n",
        sep = "", file = file, append = append)
}

create_dst_file_new <- function(fc_list = NULL, name_df_all = "all_tz_rows",
                                cache = "tzdb_cache", file = "DaylightSavingTime.R",
                                aliases = NULL){
    if(is.null(fc_list))
        fc_list <- listFinCenter()                    # "Continent/City, we need only City"
    fc_full_names <- fc_list
    
    fc_list <-  sapply(strsplit(fc_list, "/"), function(x) x[length(x)])
    ind_easter <- which(fc_list == "Easter")
    
    if(length(ind_easter) > 0) {
        fc_list[ind_easter] <- "Easter_Island"
        fc_full_names[ind_easter] <- paste0(fc_full_names[ind_easter], "_Island")
    }

    udf <- udf_sort(fc_list)
    assign(name_df_all, udf)

    ## TODO: make this saver in case other things are added to sysdata.
    nyse_early_closings <- timeDate:::nyse_early_closings
    nyse_special_closings <- timeDate:::nyse_special_closings
    
    sysdata_names <- c("nyse_early_closings",  "nyse_special_closings", name_df_all)
    save(list = sysdata_names, file = "sysdata.rda")
    
    cat(strrep("#", 80), "\n",
        "## This file was auto-generated by create_dst_file_new()\n",
        sep = "", file = file, append = FALSE)

    cat(cache, " <- new.env()\n\n", file = file, append = TRUE) # create the cache environment
    ## sysdata.r is loaded automatically by R

    for(fc in fc_list) {
        dput_fc(fc, udf, name_df_all = name_df_all, cache = cache,
                file = file)
    }
    cat("\n")

    ## TODO: !!! include the aliases
    if(!is.null(aliases))
        cat("\n", aliases, sep = "\n", file = file, append = TRUE)
    
    cat("\n",
        "## for compatibility with old versions",
        "BuenosAires <- Buenos_Aires",
        "LosAngeles <- Los_Angeles",
        "MexicoCity <- Mexico_City",
        "NewYork <- New_York",
        "Eastern <- New_York",
        "HongKong <- Hong_Kong",
        "KualaLumpur <- Kuala_Lumpur",
        "Frankfurt <- Berlin",
        "Pacific <- LosAngeles",
        sep = "\n", file = file, append = TRUE)
    cat("\n")

    ## now create a list of fin centers for listFinCenter()
    cat("\n.FinCenterList = c(",
        paste0("    \"", fc_full_names, "\"", collapse = ",\n"), ")",
        sep = "\n", file = file, append = TRUE)
    cat("\n")    
}
